Repository couplelog/lubee-client, pull requests merged in 2024-07, with the labels that each got.

#2 Etc/#1/main/initial-setting
  lubee/.eslintrc.cjs
  lubee/.prettierrc
  lubee/.stylelintrc.json
  lubee/README.md
  lubee/index.html
  lubee/package.json
  lubee/public/vite.svg
  lubee/src/App.css
  lubee/src/App.tsx
  lubee/src/assets/assets.d.ts
  lubee/src/assets/icon/logo.svg
  lubee/src/assets/image/favicon.png
  lubee/src/assets/index.ts
  lubee/src/assets/react.svg
  lubee/src/index.css
  lubee/src/main.tsx
  lubee/src/pages/ErrorPage.tsx
  lubee/src/pages/InterceptorsPage.tsx
  lubee/src/pages/LoadingPage.tsx
  lubee/src/pages/OnboardingPage.tsx
  lubee/src/router.tsx
  lubee/src/styles/globalStyle.ts
  lubee/src/styles/theme.ts
  lubee/tsconfig.app.json
  lubee/tsconfig.json
  lubee/tsconfig.node.json
  lubee/vercel.json
  lubee/vite.config.ts
  lubee/yarn.lock
Labels: 긴급, 초기세팅

#4 Etc/#2/main/github-action
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
Labels: 초기세팅

#7 Design/#5/home/common UI
  lubee/.prettierrc
  lubee/src/assets/icon/backIc.svg
  lubee/src/assets/icon/locationPointIc.svg
  lubee/src/assets/icon/mintBangIc.svg
  lubee/src/assets/icon/mintHeartIc.svg
  lubee/src/assets/icon/mintHoneyIc.svg
  lubee/src/assets/icon/mintSmileIc.svg
  lubee/src/assets/icon/mintThumbIc.svg
  lubee/src/assets/icon/profileIc.svg
  lubee/src/assets/icon/searchIc.svg
  lubee/src/assets/icon/shareBtnIc.svg
  lubee/src/assets/icon/shortborderIc.svg
  lubee/src/assets/icon/trashIc.svg
  lubee/src/assets/icon/xIc.svg
  lubee/src/assets/icon/yellowBangIc.svg
  lubee/src/assets/icon/yellowHeartIc.svg
  lubee/src/assets/icon/yellowHoneyIc.svg
  lubee/src/assets/icon/yellowSmileIc.svg
  lubee/src/assets/icon/yellowThumbIc.svg
  lubee/src/assets/image/fullPic.png
  lubee/src/assets/index.ts
  lubee/src/components/@common/EmojiBar.tsx
  lubee/src/components/@common/FullPic.tsx
  lubee/src/components/@common/Location.tsx
  lubee/src/components/SelectLocationModal.tsx
  lubee/src/components/fullPicMonth/MonthPic.tsx
  lubee/src/components/fullPicToday/DeletePicModal.tsx
  lubee/src/components/fullPicToday/EmojiDetailModal.tsx
  lubee/src/components/fullPicToday/Header.tsx
  lubee/src/components/fullPicToday/TodayPic.tsx
  lubee/src/core/bigEmojisData.ts
  lubee/src/core/fullPicData.ts
  lubee/src/core/locationData.ts
  lubee/src/core/smallEmojisData.ts
  lubee/src/pages/MonthPicPage.tsx
  lubee/src/pages/TodayPicPage.tsx
  lubee/src/pages/UploadPicPage.tsx
  lubee/src/styles/@common/commonEmojiBig.ts
  lubee/src/styles/@common/commonEmojiSmall.ts
  lubee/src/styles/@common/commonPic.ts
  lubee/src/styles/globalStyle.ts
  lubee/src/styles/theme.ts
  lubee/src/types/EmojisDataTypes.ts
Labels: design

#9 Design/#6/login/UI
  lubee/src/assets/icon/copy.svg
  lubee/src/assets/icon/logoGray.svg
  lubee/src/assets/icon/lubeeCode.svg
  lubee/src/assets/icon/symbol.svg
  lubee/src/assets/icon/symbolLogin.svg
  lubee/src/assets/index.ts
  lubee/src/components/onboarding/CopyCodeModal.tsx
  lubee/src/components/onboarding/Header.tsx
  lubee/src/components/onboarding/NumberBox.tsx
  lubee/src/components/onboarding/OnboardingBtn.tsx
  lubee/src/components/onboarding/TitleBox.tsx
  lubee/src/pages/LoginPage.tsx
  lubee/src/pages/OnboardingPage.tsx
  lubee/src/pages/SplashPage.tsx
  lubee/src/router.tsx
  lubee/src/styles/BtnStyle.ts
  lubee/src/styles/theme.ts
  lubee/yarn.lock
Labels: design

#14 Feat/#8/home/calendar
  lubee/.stylelintrc.json
  lubee/index.html
  lubee/package.json
  lubee/src/@common/core/calendarData.ts
  lubee/src/@common/core/imagesData.ts
  lubee/src/@common/types/EmojisDataTypes.ts
  lubee/src/@styles/style.d.ts
  lubee/src/@styles/theme.ts
  lubee/src/assets/icon/exploreDeactivateIc.svg
  lubee/src/assets/icon/homeActivateIc.svg
  lubee/src/assets/icon/homeDeactivateIc.svg
  lubee/src/assets/icon/honeyMonthIc.svg
  lubee/src/assets/icon/myActivateIc.svg
  lubee/src/assets/icon/myDeactivateIc.svg
  lubee/src/assets/image/blankImg.png
  lubee/src/assets/image/modalImg.png
  lubee/src/assets/index.ts
  lubee/src/error/index.tsx
  lubee/src/fullpic/components/EmojiDetailModal.tsx
  lubee/src/fullpic/components/FullpicHeader.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/date/index.tsx
  lubee/src/fullpic/index.tsx
  lubee/src/fullpic/one/components/OneContainer.tsx
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/components/HomeFooter.tsx
  lubee/src/home/components/HomeHeader.tsx
  lubee/src/home/index.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/Comment.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/month/index.tsx
  lubee/src/home/month/types/CalInfoTypes.ts
  lubee/src/home/today/index.tsx
  lubee/src/mypage/components/MypageFooter.tsx
  lubee/src/mypage/index.tsx
  lubee/src/onboarding/components/YellowBox.tsx
  lubee/src/router.tsx
  lubee/yarn.lock
Labels: feat, design

#17 Feat/#15/home/pic upload
  lubee/package.json
  lubee/src/@common/core/imagesData.ts
  lubee/src/@common/recoil/atom.ts
  lubee/src/@common/types/EmojisDataTypes.ts
  lubee/src/App.tsx
  lubee/src/assets/index.ts
  lubee/src/home/components/BlankImgBtn.tsx
  lubee/src/home/components/DateDetailModal.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/today/index.tsx
  lubee/src/upload/index.tsx
  lubee/src/upload/location/index.tsx
  lubee/src/upload/pic/index.tsx
  lubee/yarn.lock
Labels: feat, design

#18 BtnWrapper 경로 수정 및 적용
  lubee/src/@styles/btnStyle.ts
  lubee/src/@styles/globalStyle.ts
  lubee/src/fullpic/components/FullpicHeader.tsx
  lubee/src/home/components/HomeFooter.tsx
  lubee/src/mypage/components/MypageFooter.tsx
  lubee/src/onboarding/custom/index.tsx
  lubee/src/onboarding/index.tsx
  lubee/src/onboarding/profile/index.tsx
  lubee/src/upload/components/SelectLocationModal.tsx
  lubee/src/upload/location/index.tsx
  lubee/src/upload/pic/index.tsx
Labels: design

#20 사용자가 선택한 프로필 아이콘 각 페이지에 불러오기 로직
  lubee/src/@common/core/profileIconsData.ts
  lubee/src/@common/types/EmojisDataTypes.ts
  lubee/src/@common/utils/getIconSrc.ts
  lubee/src/assets/icon/mintProfile1Ic.svg
  lubee/src/assets/icon/mintProfile2Ic.svg
  lubee/src/assets/icon/mintProfile3Ic.svg
  lubee/src/assets/icon/mintProfile4Ic.svg
  lubee/src/assets/icon/mintProfile5Ic.svg
  lubee/src/assets/icon/mintProfile6Ic.svg
  lubee/src/assets/index.ts
  lubee/src/fullpic/components/EmojiDetailModal.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/Comment.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
Labels: feat

#21 Design/#16/home/UI
  lubee/src/@common/core/ProfileCustomIconsData.ts
  lubee/src/@common/recoil/atom.ts
  lubee/src/@common/types/EmojisDataTypes.ts
  lubee/src/@styles/style.d.ts
  lubee/src/@styles/theme.ts
  lubee/src/assets/icon/checkIc.svg
  lubee/src/assets/icon/checkYellowIc.svg
  lubee/src/assets/icon/honeyIc.svg
  lubee/src/assets/icon/otherProfileIc.svg
  lubee/src/assets/icon/pencilIc.svg
  lubee/src/assets/icon/plusIc.svg
  lubee/src/assets/icon/progressBar1Ic.svg
  lubee/src/assets/icon/progressBar2Ic.svg
  lubee/src/assets/icon/progressBar3Ic.svg
  lubee/src/assets/icon/progressBar4Ic.svg
  lubee/src/assets/index.ts
  lubee/src/home/components/BlankImgBtn.tsx
  lubee/src/home/today/components/CommentInputBox.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/DateBox.tsx
  lubee/src/home/today/components/HoneyIconContainer.tsx
  lubee/src/home/today/components/ProfileBox.tsx
  lubee/src/home/today/components/Title.tsx
  lubee/src/home/today/index.tsx
  lubee/src/onboarding/anniversary/index.tsx
  lubee/src/onboarding/birth/index.tsx
  lubee/src/onboarding/code/index.tsx
  lubee/src/onboarding/complete/components/TitleBox.tsx
  lubee/src/onboarding/complete/index.tsx
  lubee/src/onboarding/components/ProgressBar.tsx
  lubee/src/onboarding/components/TitleBox.tsx
  lubee/src/onboarding/components/YellowBox.tsx
  lubee/src/onboarding/connect/index.tsx
  lubee/src/onboarding/custom/index.tsx
  lubee/src/onboarding/index.tsx
  lubee/src/onboarding/profile/index.tsx
  lubee/src/router.tsx
Labels: design

#23 Design/#19/date detail modal/common UI
  lubee/src/@common/components/EmojiTag.tsx
  lubee/src/@common/components/FullPicContainer.tsx
  lubee/src/@common/components/LocationTag.tsx
  lubee/src/@common/components/SmallEmojiIcons.tsx
  lubee/src/@common/core/ProfileCustomIconsData.ts
  lubee/src/@common/core/bigEmojisData.ts
  lubee/src/@common/core/emojisData.ts
  lubee/src/@common/core/fullPicData.ts
  lubee/src/@common/core/imagesData.ts
  lubee/src/@common/core/smallEmojisData.ts
  lubee/src/@common/types/EmojisDataTypes.ts
  lubee/src/@common/utils/getEmojiSrc.ts
  lubee/src/assets/index.ts
  lubee/src/fullpic/components/EmojiDetailModal.tsx
  lubee/src/fullpic/components/FullpicHeader.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/one/components/OneContainer.tsx
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/components/HomePicBox.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/month/index.tsx
  lubee/src/home/today/components/CommentInputBox.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/index.tsx
  lubee/src/onboarding/custom/index.tsx
  lubee/src/upload/pic/index.tsx
Labels: feat, refactor, design

#24 Feat/#22/home/comment input
  lubee/src/@common/types/EmojisDataTypes.ts
  lubee/src/assets/icon/editXIc.svg
  lubee/src/assets/index.ts
  lubee/src/home/today/components/CommentBox.tsx
  lubee/src/home/today/components/CommentInputBox.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/MyCommentModal.tsx
  lubee/src/home/today/components/PartnerCommentModal.tsx
  lubee/src/home/today/index.tsx
  lubee/src/onboarding/custom/index.tsx
Labels: feat, design

#26 Design/#25/congrats/UI
  lubee/src/@common/core/emojisData.ts
  lubee/src/@common/core/fullPicData.ts
  lubee/src/@common/core/profileIconsData.ts
  lubee/src/@common/recoil/atom.ts
  lubee/src/@common/types/CommonTypes.ts
  lubee/src/@common/utils/getProfileIconSrc.ts
  lubee/src/assets/icon/congratsIc.svg
  lubee/src/assets/icon/fifthHoneyIc.svg
  lubee/src/assets/icon/firstHoneyIc.svg
  lubee/src/assets/index.ts
  lubee/src/congrats/components/CongratsTitleBox.tsx
  lubee/src/congrats/fifth/index.tsx
  lubee/src/congrats/first/index.tsx
  lubee/src/congrats/index.tsx
  lubee/src/congrats/join/index.tsx
  lubee/src/fullpic/components/EmojiDetailModal.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/one/components/OneContainer.tsx
  lubee/src/home/components/HomePicBox.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/MyCommentModal.tsx
  lubee/src/home/today/components/PartnerCommentModal.tsx
  lubee/src/home/today/components/ProfileBox.tsx
  lubee/src/home/today/components/TodayTitle.tsx
  lubee/src/home/today/index.tsx
  lubee/src/home/today/types/CommentModalTypes.ts
  lubee/src/layout/OnboardingLayout.tsx
  lubee/src/main.tsx
  lubee/src/onboarding/anniversary/index.tsx
  lubee/src/onboarding/birth/index.tsx
  lubee/src/onboarding/code/index.tsx
  lubee/src/onboarding/complete/index.tsx
  lubee/src/onboarding/components/OnboardingHeader.tsx
  lubee/src/onboarding/components/OnboardingTitleBox.tsx
  lubee/src/onboarding/connect/index.tsx
  lubee/src/onboarding/custom/index.tsx
  lubee/src/onboarding/index.tsx
  lubee/src/onboarding/profile/index.tsx
  lubee/src/router.tsx
Labels: design

#28 Design/#27/home today/toggle UI
  lubee/src/assets/icon/backSmallIc.svg
  lubee/src/assets/icon/forwardIc.svg
  lubee/src/assets/icon/toggleHoneyIc.svg
  lubee/src/assets/icon/togglePastIc.svg
  lubee/src/assets/index.ts
  lubee/src/home/components/HomePicBox.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/month/index.tsx
  lubee/src/home/today/components/ProfileBox.tsx
  lubee/src/home/today/components/Toggle.tsx
  lubee/src/home/today/components/ToggleCalendar.tsx
  lubee/src/home/today/index.tsx
Labels: feat, design

#31 Design/#30/home/UI
  lubee/src/@common/core/fullPicData.ts
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/CommentBox.tsx
  lubee/src/home/today/components/MyCommentModal.tsx
  lubee/src/onboarding/components/rolldate/DatePickerScroll.tsx
  lubee/src/onboarding/components/rolldate/rolldate.min.js
Labels: feat, design

#32 Design/#29/home/design qa
  lubee/src/@common/components/EmojiTag.tsx
  lubee/src/@common/components/FullPicContainer.tsx
  lubee/src/@common/components/LocationTag.tsx
  lubee/src/@common/core/calendarData.ts
  lubee/src/@common/core/fullPicData.ts
  lubee/src/@common/core/locationData.ts
  lubee/src/@common/types/CommonTypes.ts
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/components/HomePicBox.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/Comment.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ToggleCalendar.tsx
  lubee/src/upload/components/SelectLocationModal.tsx
  lubee/src/upload/location/index.tsx
Labels: feat, refactor, design

#38 Design/#33/mypage/UI
  lubee/src/@common/core/profileIconsData.ts
  lubee/src/@common/core/profileOnboardingData.ts
  lubee/src/@common/types/CommonTypes.ts
  lubee/src/@common/utils/getHoverProfileIconSrc.ts
  lubee/src/assets/icon/bannerIc.svg
  lubee/src/assets/icon/editIc.svg
  lubee/src/assets/icon/honeyYellowIc.svg
  lubee/src/assets/icon/mintProfileStroke1Ic.svg
  lubee/src/assets/icon/mintProfileStroke2Ic.svg
  lubee/src/assets/icon/mintProfileStroke3Ic.svg
  lubee/src/assets/icon/mintProfileStroke4Ic.svg
  lubee/src/assets/icon/mintProfileStroke5Ic.svg
  lubee/src/assets/icon/mintProfileStroke6Ic.svg
  lubee/src/assets/icon/nextIc.svg
  lubee/src/assets/icon/playIc.svg
  lubee/src/assets/icon/settingIc.svg
  lubee/src/assets/image/album1Img.png
  lubee/src/assets/image/album2Img.png
  lubee/src/assets/image/collect2Img.png
  lubee/src/assets/image/collect3Img.png
  lubee/src/assets/image/collectImg.png
  lubee/src/assets/index.ts
  lubee/src/home/today/components/TodayProfileBox.tsx
  lubee/src/home/today/index.tsx
  lubee/src/mypage/components/AlbumsContainer.tsx
  lubee/src/mypage/components/Banner.tsx
  lubee/src/mypage/components/HoneyBox.tsx
  lubee/src/mypage/components/MypageBlankImgBtn.tsx
  lubee/src/mypage/components/MypageProfileBox.tsx
  lubee/src/mypage/components/SaveContainer.tsx
  lubee/src/mypage/components/TabBar.tsx
  lubee/src/mypage/index.tsx
  lubee/src/onboarding/custom/index.tsx
Labels: design

#41 Feat/#37/home/calendar
  lubee/package.json
  lubee/src/@common/core/calendarData.ts
  lubee/src/@common/utils/dateFormat.ts
  lubee/src/@common/utils/toast.ts
  lubee/src/@styles/toast.ts
  lubee/src/App.tsx
  lubee/src/home/components/HomeFooter.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/index.tsx
  lubee/src/home/today/components/ToggleCalendar.tsx
  lubee/src/mypage/components/MypageFooter.tsx
  lubee/yarn.lock
Labels: feat

#42 Feat/#39/onboarding/date input
  lubee/src/@common/types/rolldate.d.ts
  lubee/src/@styles/style.d.ts
  lubee/src/@styles/theme.ts
  lubee/src/assets/icon/playIc.svg
  lubee/src/assets/icon/rewindIc.svg
  lubee/src/assets/image/album1Img.png
  lubee/src/assets/image/album2Img.png
  lubee/src/assets/image/collect2Img.png
  lubee/src/assets/image/collect3Img.png
  lubee/src/assets/image/collectImg.png
  lubee/src/assets/index.ts
  lubee/src/mypage/components/HoneyBox.tsx
  lubee/src/mypage/components/RewindBtn.tsx
  lubee/src/mypage/index.tsx
  lubee/src/onboarding/anniversary/index.tsx
  lubee/src/onboarding/birth/index.tsx
  lubee/src/onboarding/components/DateInput.tsx
  lubee/src/onboarding/components/rolldate/DatePickerScroll.tsx
  lubee/src/onboarding/components/rolldate/rolldate.es.js
  lubee/tsconfig.json
  lubee/tsconfig.node.json
  lubee/vite.config.js
Labels: feat, design

#43 Feat/#40/location/detect input
  lubee/src/@common/core/locationData.ts
  lubee/src/@common/recoil/atom.ts
  lubee/src/upload/components/SelectLocationModal.tsx
  lubee/src/upload/index.tsx
  lubee/src/upload/location/index.tsx
  lubee/src/upload/pic/index.tsx
  lubee/src/upload/types/LocationDataTypes.ts
Labels: feat

#45 Feat/#44/upload/show uploaded
  lubee/src/@common/components/FullPicContainer.tsx
  lubee/src/@common/utils/toast.ts
  lubee/src/home/components/BlankImgBtn.tsx
  lubee/src/home/utils/readPic.ts
  lubee/src/upload/pic/index.tsx
Labels: feat, design

#48 Feat/#47/onboarding/input focus
  lubee/index.html
  lubee/src/assets/image/urlImg.png
  lubee/src/onboarding/code/index.tsx
  lubee/src/onboarding/components/DateInput.tsx
  lubee/src/onboarding/connect/index.tsx
Labels: feat

#50 Feat/#34/login/kakao login
  lubee/src/@common/api/api.ts
  lubee/src/@common/types/Response.ts
  lubee/src/App.tsx
  lubee/src/login/components/LoginCallback.tsx
  lubee/src/login/constants/kakaoLink.ts
  lubee/src/login/hooks/usePostLogin.ts
  lubee/src/login/index.tsx
  lubee/src/login/types/loginProps.ts
  lubee/src/login/utils/token.ts
  lubee/src/onboarding/connect/api/getLubeeCode.ts
  lubee/src/onboarding/connect/hooks/useGetLubeeCode.ts
  lubee/src/onboarding/connect/index.tsx
Labels: 긴급, feat

#52 feat: 러비코드 조회 API
  lubee/src/onboarding/api/getLubeeCode.ts
  lubee/src/onboarding/connect/index.tsx
  lubee/src/onboarding/hooks/useGetLubeeCode.ts
Labels: feat

#54 Design/#49/onboarding/design qa
  lubee/index.html
  lubee/src/@common/components/EmojiTag.tsx
  lubee/src/@common/components/LocationTag.tsx
  lubee/src/@common/core/calendarData.ts
  lubee/src/@common/utils/getEmojiSrc.ts
  lubee/src/@styles/globalStyle.ts
  lubee/src/@styles/picStyle.ts
  lubee/src/@styles/style.d.ts
  lubee/src/@styles/theme.ts
  lubee/src/@styles/toast.ts
  lubee/src/api/customAxios.ts
  lubee/src/assets/icon/locationPointSmallIc.svg
  lubee/src/assets/icon/plusClickedIc.svg
  lubee/src/assets/icon/progressBar3Ic.svg
  lubee/src/assets/icon/shareBtnIc.svg
  lubee/src/assets/index.ts
  lubee/src/congrats/index.tsx
  lubee/src/fullpic/components/EmojiDetailModal.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/components/HomePicBox.tsx
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/today/components/CommentBox.tsx
  lubee/src/home/today/components/DateBox.tsx
  lubee/src/home/today/index.tsx
  lubee/src/login/index.tsx
  lubee/src/onboarding/components/DateInput.tsx
  lubee/src/onboarding/components/ProgressBar.tsx
  lubee/src/onboarding/components/YellowBox.tsx
  lubee/src/onboarding/connect/index.tsx
  lubee/src/upload/location/index.tsx
Labels: 긴급, feat, design

#56 feat: 러비코드 연결 API
  lubee/src/onboarding/api/postLubeeCode.ts
  lubee/src/onboarding/code/index.tsx
  lubee/src/onboarding/hooks/usePostLubeeCode.ts
Labels: feat

#67 기록 불러오기 API 구현
  lubee/src/@common/components/FullPicContainer.tsx
  lubee/src/@common/utils/dateFormat.ts
  lubee/src/fullpic/api/getOnePic.ts
  lubee/src/fullpic/components/FullpicHeader.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/date/index.tsx
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/api/getSpecificCalendar.ts
  lubee/src/home/components/BlankImgBtn.tsx
  lubee/src/home/hooks/useGetSpecificCalendar.ts
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/month/components/MonthPicBox.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/TodayPicBox.tsx
  lubee/src/home/today/components/Toggle.tsx
  lubee/src/login/hooks/usePostLogin.ts
  lubee/src/login/types/loginProps.ts
  lubee/src/upload/api/postUploadPic.ts
  lubee/src/upload/hooks/usePostUploadPic.ts
  lubee/src/upload/pic/index.tsx
Labels: feat

#71 사진 업로드 API 구현
  lubee/src/@common/components/EmojiTag.tsx
  lubee/src/fullpic/api/deletePic.ts
  lubee/src/fullpic/components/DeletePicModal.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/date/index.tsx
  lubee/src/fullpic/hooks/useDeletePic.ts
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/components/BlankImgBtn.tsx
  lubee/src/home/month/components/MonthPicBox.tsx
  lubee/src/home/today/components/TodayPicBox.tsx
  lubee/src/upload/api/postUploadPic.ts
  lubee/src/upload/pic/index.tsx
Labels: feat

#75 pr68을 develop으로의 머지 해결
  lubee/src/@common/utils/dateFormat.ts
  lubee/src/assets/icon/todayHoney0Ic.svg
  lubee/src/assets/icon/todayHoney1Ic.svg
  lubee/src/assets/icon/todayHoney2Ic.svg
  lubee/src/assets/icon/todayHoney3Ic.svg
  lubee/src/assets/icon/todayHoney4Ic.svg
  lubee/src/assets/icon/todayHoney5Ic.svg
  lubee/src/assets/index.ts
  lubee/src/fullpic/api/deletePic.ts
  lubee/src/home/api/getMonthHoney.ts
  lubee/src/home/api/getTodayDateComment.ts
  lubee/src/home/api/getTodayHoney.ts
  lubee/src/home/api/postDateComment.ts
  lubee/src/home/api/updateDateComment.ts
  lubee/src/home/components/CommentBox.tsx
  lubee/src/home/components/MyCommentModal.tsx
  lubee/src/home/components/PartnerCommentModal.tsx
  lubee/src/home/hooks/useGetMonthHoney.ts
  lubee/src/home/hooks/useGetTodayDateComment.ts
  lubee/src/home/hooks/useGetTodayHoney.ts
  lubee/src/home/hooks/usePostDateComment.ts
  lubee/src/home/hooks/useUpdateDateComment.ts
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/Comment.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/HoneyIconContainer.tsx
  lubee/src/home/today/index.tsx
  lubee/src/home/utils/commentIdStroage.ts
  lubee/src/mypage/api/getTotalHoney.ts
  lubee/src/mypage/hooks/useGetTotalHoney.ts
  lubee/src/mypage/index.tsx
  lubee/src/onboarding/api/postLubeeCode.ts
  lubee/src/onboarding/components/YellowBox.tsx
  lubee/src/onboarding/connect/index.tsx
  lubee/src/onboarding/hooks/usePostLubeeCode.ts
Labels: 긴급, merge, feat

#79 헤더에 토큰이 안담기는 문제 해결
  lubee/src/settings/hooks/useSetInterceptors.ts
Labels: 긴급

#80 온보딩 정보 post API 구현
  lubee/src/@common/core/profileIconsData.ts
  lubee/src/@common/recoil/atom.ts
  lubee/src/onboarding/anniversary/index.tsx
  lubee/src/onboarding/birth/index.tsx
  lubee/src/onboarding/custom/index.tsx
  lubee/src/onboarding/profile/index.tsx
Labels: feat

#77 커플 정보 받아오기 API로 정보 출력
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/TodayProfileBox.tsx
  lubee/src/home/today/components/TodayTitle.tsx
  lubee/src/mypage/components/MypageProfileBox.tsx
  lubee/src/mypage/index.tsx
Labels: feat

#84 사귄 일수 출력 API 구현
  lubee/src/home/api/getLoveDay.ts
  lubee/src/home/hooks/useGetLoveDay.ts
  lubee/src/home/today/index.tsx
  lubee/src/settings/hooks/useSetInterceptors.ts
Labels: feat

#86 코멘트 관련 API 수정
  lubee/src/home/api/getTodayDateComment.ts
  lubee/src/home/api/postDateComment.ts
  lubee/src/home/api/updateDateComment.ts
  lubee/src/home/components/CommentBox.tsx
  lubee/src/home/components/MyCommentModal.tsx
  lubee/src/home/hooks/useGetTodayDateComment.ts
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/types/CommentModalTypes.ts
  lubee/src/home/utils/commentIdStroage.ts
Labels: feat

#90 feat: comment_first, comment_second로 수정된 오늘의 데이트 코멘트 조회 API
  lubee/src/home/api/getTodayDateComment.ts
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/settings/hooks/useSetInterceptors.ts
Labels: feat

#92 상대 코멘트 출력 안되는 문제 해결
  lubee/src/home/components/CommentBox.tsx
  lubee/src/home/today/index.tsx
Labels: feat

#93 이모지 반응 update, post API 구현
  lubee/package-lock.json
  lubee/src/@common/api/postReaction.ts
  lubee/src/@common/api/updateReaction.ts
  lubee/src/@common/components/EmojiBar.tsx
  lubee/src/@common/components/EmojiTag.tsx
  lubee/src/@common/components/LocationTag.tsx
  lubee/src/@common/hooks/usePostReaction.ts
  lubee/src/@common/hooks/useUpdateReaction.ts
  lubee/src/@common/utils/getEmojiSrc.ts
  lubee/src/App.tsx
  lubee/src/fullpic/api/getOnePic.ts
  lubee/src/fullpic/components/DeletePicModal.tsx
  lubee/src/fullpic/components/FullpicHeader.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/date/index.tsx
  lubee/src/fullpic/hooks/useGetOnePic.ts
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/hooks/useGetSpecificCalendar.ts
  lubee/src/home/index.tsx
  lubee/src/home/month/components/MonthHomeHeader.tsx
  lubee/src/home/month/components/MonthPicBox.tsx
  lubee/src/home/month/index.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/TodayHomeHeader.tsx
  lubee/src/home/today/components/TodayPicBox.tsx
  lubee/src/home/today/index.tsx
  lubee/src/home/utils/readPic.ts
  lubee/src/loading/index.tsx
  lubee/src/login/hooks/usePostLogin.ts
  lubee/src/upload/api/postUploadPic.ts
  lubee/src/upload/pic/index.tsx
Labels: feat, design

#95 emoji post/update 경우의 수 수정, fullpic/date 페이지네이션으로 변경
  lubee/src/@common/components/EmojiBar.tsx
  lubee/src/fullpic/components/EmojiDetailModal.tsx
  lubee/src/fullpic/components/FullpicHeader.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/date/index.tsx
  lubee/src/fullpic/one/index.tsx
Labels: feat, design

#96 기록을 추가했을 경우에만 꿀 개수에 따라 축하페이지로 이동하기
  lubee/src/home/hooks/useGetTodayHoney.ts
  lubee/src/home/today/index.tsx
  lubee/src/loading/index.tsx
Labels: feat

#99 home 페이지 기능 QA
  lubee/src/assets/icon/leftArrowIc.svg
  lubee/src/assets/icon/rightArrowIc.svg
  lubee/src/assets/index.ts
  lubee/src/error/index.tsx
  lubee/src/fullpic/components/EmojiDetailModal.tsx
  lubee/src/fullpic/date/components/DateContainer.tsx
  lubee/src/fullpic/date/index.tsx
  lubee/src/home/hooks/useGetCalendar.ts
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/MonthHomeHeader.tsx
  lubee/src/home/month/components/MonthPicBox.tsx
  lubee/src/home/month/index.tsx
  lubee/src/home/today/components/TodayHomeHeader.tsx
  lubee/src/home/today/components/TodayPicBox.tsx
  lubee/src/mypage/components/MypageProfileBox.tsx
  lubee/src/upload/components/SelectLocationModal.tsx
  lubee/src/upload/hooks/useGetLocationSearch.ts
  lubee/src/upload/location/index.tsx
  lubee/src/upload/pic/index.tsx
Labels: feat, refactor, design

#103 오늘 업로드, 로그인 전 403에러 해결
  lubee/src/@common/hooks/useGetCouplesInfo.ts
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/TodayPicBox.tsx
  lubee/src/home/today/components/Toggle.tsx
  lubee/src/home/today/index.tsx
  lubee/src/login/hooks/usePostLogin.ts
Labels: feat

#104 페이지네이션 할 때도 리액션 통신
  lubee/src/@common/recoil/atom.ts
  lubee/src/fullpic/components/FullpicHeader.tsx
  lubee/src/fullpic/date/index.tsx
  lubee/src/home/utils/readPic.ts
Labels: refactor

#106 로그인 후 온보딩으로 이동 문제 해결, 오늘 홈으로 버튼 문제 해결, 모달에서 코멘트 위치 문제 해결
  lubee/src/@common/hooks/useGetCouplesInfo.ts
  lubee/src/congrats/index.tsx
  lubee/src/home/components/CommentBox.tsx
  lubee/src/home/components/MyCommentModal.tsx
  lubee/src/home/components/PartnerCommentModal.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/types/CommentModalTypes.ts
  lubee/src/login/hooks/usePostLogin.ts
Labels: refactor, 배포에러

#107 상대 코멘트 안 보이는 문제 해결, 각종 디자인 수정
  lubee/index.html
  lubee/src/@styles/theme.ts
  lubee/src/@styles/toast.ts
  lubee/src/home/components/MyCommentModal.tsx
  lubee/src/home/hooks/useGetTodayDateComment.ts
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/mypage/components/MypageBlankImgBtn.tsx
  lubee/src/mypage/components/RewindBtn.tsx
  lubee/src/onboarding/anniversary/index.tsx
  lubee/src/onboarding/birth/index.tsx
  lubee/src/onboarding/code/index.tsx
  lubee/src/onboarding/components/DateInput.tsx
  lubee/src/onboarding/connect/index.tsx
Labels: feat, design
