Repository couplelog/lubee-client, pull requests merged in 2024-08, with the labels that each got.

#108 기능, 디자인 qa -> deploy/v3로 머지
  lubee/index.html
  lubee/src/@common/components/LocationTag.tsx
  lubee/src/@common/core/calendarData.ts
  lubee/src/@common/hooks/useGetCouplesInfo.ts
  lubee/src/@styles/toast.ts
  lubee/src/App.tsx
  lubee/src/assets/icon/locationPointSmallIc.svg
  lubee/src/congrats/index.tsx
  lubee/src/fullpic/one/index.tsx
  lubee/src/home/components/CommentBox.tsx
  lubee/src/home/components/MyCommentModal.tsx
  lubee/src/home/components/PartnerCommentModal.tsx
  lubee/src/home/hooks/useGetSpecificCalendar.ts
  lubee/src/home/month/components/CalContainer.tsx
  lubee/src/home/month/components/DateDetailModal.tsx
  lubee/src/home/month/components/MonthPicBox.tsx
  lubee/src/home/month/index.tsx
  lubee/src/home/today/components/ContentContainer.tsx
  lubee/src/home/today/components/ToggleCalendar.tsx
  lubee/src/honey/fifth/index.tsx
  lubee/src/honey/first/index.tsx
  lubee/src/honey/index.tsx
  lubee/src/loading/index.tsx
  lubee/src/login/hooks/usePostLogin.ts
  lubee/src/mypage/components/RewindBtn.tsx
  lubee/src/onboarding/components/YellowBox.tsx
  lubee/src/onboarding/connect/index.tsx
  lubee/src/onboarding/hooks/useGetLubeeCode.ts
Labels: merge, qa

#109 최종 디자인QA 반영
  lubee/src/assets/icon/loadingIc.svg
  lubee/src/assets/index.ts
  lubee/src/loading/index.tsx
  lubee/src/onboarding/connect/index.tsx
  node_modules/.yarn-integrity
  yarn.lock
Labels: design

#110 디자인 QA -> deploy/v3로 머지
  lubee/src/@common/components/LocationTag.tsx
Labels: design

#116 Feat/#114/setting/setting api
  lubee/src/onboarding/index.tsx
  lubee/src/setting/account/index.tsx
  lubee/src/setting/api/getCouplesBreak.ts
  lubee/src/setting/api/getSignOut.ts
  lubee/src/setting/couple/index.tsx
  lubee/src/setting/hooks/useGetCouplesBreak.ts
  lubee/src/setting/hooks/useGetSignOut.ts
Labels: feat
